# --- Import libraries ---
import numpy as np
import pandas as pd
# Matplotlib is imported but not strictly necessary if only generating the table

# --- Resilience Function (Eq. 5) ---
def resilience(A, E, n):
    # Base Critical Threshold (Ac) defined by Eq. 3
    Ac = E / n
    return 1 / (1 + np.exp(-(A - Ac)))

# --- Sensitivity Derivatives (Eq. 6, 7, 8) ---
def dR_dA(A, E, n):
    R = resilience(A, E, n)
    return R * (1 - R)

def dR_dE(A, E, n):
    R = resilience(A, E, n)
    # Sensitivity to external pressure (Eq. 7)
    return -(1/n) * R * (1 - R)

def dR_dn(A, E, n):
    R = resilience(A, E, n)
    # Sensitivity to complexity (Eq. 8)
    return (E / n**2) * R * (1 - R)

# --- Example values (Matches Table 1 data) ---
A_values = [14, 24, 13, 12, 5]
E_values = [26, 39, 34, 30, 27]
n_values = [2, 2, 4, 3, 4]

results = []
for A, E, n in zip(A_values, E_values, n_values):
    R = resilience(A, E, n)
    Ac = E / n # Calculate Ac for the table column
    dA = dR_dA(A, E, n)
    dE = dR_dE(A, E, n)
    dn = dR_dn(A, E, n)
    # Results include Ac and rounded R values for the table
    results.append([A, E, n, round(Ac, 2), round(R, 2), round(dA, 3), round(dE, 3), round(dn, 3)])

# DataFrame definition
col_names = ["A", "E", "n", "Ac", "R(A,E,n)", "dR/dA", "dR/dE", "dR/dn"]
df = pd.DataFrame(results, columns=col_names)

print("--- Table 1 Simulation Results ---")
print(df)
# Figure 1 is generated by the 'resilience_curve_plot.py' script.
